name: 'Set up Python'
description: 'Sets up Python 3.10 and installs dependencies'
inputs:
  input1:
    description: 'First input to the script'
    required: true
  input2:
    description: 'Second input to the script'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Python
      shell: bash
      run: |
        apt-get update
        apt-get install -y python3 python3-venv python3-pip
        python3 --version 

    - name: Set up virtual environment and install requirements
      shell: bash
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r  python-src/requirements.txt 
        python python-src/script.py --input1 "${{ inputs.input1 }}" --input2 "${{ inputs.input2 }}"

