name: Advanced-1 Workflow

on:
  push:
    branches:     # This workflow will run on push to the main branch
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18    # Use Node.js 18 as the container image for JavaScript actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Python Composite Action
        uses: ./github/actions/jenkins-python-actions
        with:
          input1: "Wednesday"
          input2: "Thursday"